### ISSUE TITLE
Compiler tools not found

### ISSUE THREAD

**Issue by harshana5** [jugglingnutcase/language-powershell#39]
Hi,

I'm new to atom, when try to install powershell package I'm getting Compiler tools not found error. I'm guessing I missed a config somewhere. Could you please give me hand with this or point me to a wiki somewhere.

Thanks 

H.

**Comment by jugglingnutcase** [comment]
Hi @harshana5 :smile: 

i don't think that issue is related to this package because this package is only providing a language grammar and some powershell-related snippets. There's nothing going out to a compiler here. i think that another package would be causing your problem, what other packages do you have installed?

Maybe taking a look through [Atom's debugging guide](https://atom.io/docs/latest/hacking-atom-debugging) will help you pin down the issue.

Do you have Omnisharp installed by any chance? Maybe they are using some compiler tools?

**Comment by jugglingnutcase** [comment]
Closing, but i can continue to help if you need it.

**Comment by harshana5** [comment]
Hi,

I just installed Atom, then I searched for your package and installed it.

Question do I need to have VS2010 ? I have visual studio 2013, could it be the install package looking for a dependency on VS 2010 ?

I am running vs2013 on a windows 7

**Comment by jugglingnutcase** [comment]
Nope, there's no dependencies on VS. This package just provides syntax highlighting for powershell files, not much more.

**Comment by harshana5** [comment]
hmmm odd, this is the screen shot of what i'm getting when I try to install the package. 

![image](https://cloud.githubusercontent.com/assets/4476421/7381068/2f415d36-ee54-11e4-865b-02725c086880.png)

**Comment by jugglingnutcase** [comment]
Thanks for the screenshot, that was very helpful :+1:

Looks like this might be related to an issue in apm that was recently closed: atom/apm#141. Since you're probably using the latest version of Atom, you might be getting bit by this one!

Looks like it should be resolved in the next release.

**Comment by harshana5** [comment]
Yeah, I saw few people had similar issues with installing packages. I will have a play on the next release an see. 

Thanks for your help.

**Comment by jugglingnutcase** [comment]
You're welcome :sunglasses: 

That one caught me off guard!
