### ISSUE TITLE
After saving the files becomes unusable

### ISSUE THREAD

**Issue by yvdmeij** [jugglingnutcase/language-powershell#68]
Hi, on my Mac I tried the add-on, but once I save the file it won't work. 
I save it as .ps1

**Comment by jrsconfitto** [comment]
Hi, did you run into a problem while saving a ps1 file in Atom while using this extension? I'm unable to reproduce the issue, are you able to send along the file for me to test? Or reproduction steps?

**Comment by yvdmeij** [comment]
Yes, the problem occurs with any .ps1 file. Even after making a change such as adding a space and then saving the file, it becomes unusable. I have tried it again today just to make sure it wasn't my computer.

So in the mean time I have used Visual Studio Code and this works without any problems. 

I will post a picture so you can see what happens. 

You can find the file I used when I ran into the problem at my repo:
[Caesar Cipher](https://github.com/Yagooza/UiA_hacking/blob/master/Oppgave_4.2.1/Caesar_Cipher_Encrypt.ps1)

As you can see in the picture the file worked just fine before I saved it with Atom.
Actually the error message is longer, there are 57 error messages in total.

<img width="823" alt="Skjermbilde 2019-09-13 kl  22 28 13" src="https://user-images.githubusercontent.com/35783118/64892879-dbe13d00-d675-11e9-98d7-270fa876abba.png">

**Comment by jrsconfitto** [comment]
I'm able to make edits to your linked file in Atom with this package installed:

![issue repro](https://user-images.githubusercontent.com/238079/64994114-c94d4a80-d8a5-11e9-81db-08605bdac2d8.gif)

I'm confused about the screenshot you sent. This package doesn't run ps1 files, it's a language grammar used for syntax highlighting in Atom.

**Comment by yvdmeij** [comment]
Well yes, you are right. I'm sorry for my poor explanation. I'm perfectly able to edit the file and save it afterwards. This gives no problems in Atom. And it highlights the syntax. 

Though, saving the file with Atom makes the file unusable. This is also happening without your package. 

I just assumed, that since your package is meant to highlight ps1 syntax. That it would  also make Atom able to save the file, without making it unusable.

Are you able to run the file in powershell after saving the file in Atom?

**Comment by jrsconfitto** [comment]
I'm uncomfortable running that particular script because I do not understand it (sorry!) but I can open, save, and run some of my own scripts:

![issue demo](https://user-images.githubusercontent.com/238079/65046827-57214800-d92f-11e9-9baf-6531f902884c.gif)

The issues I'm seeing in your screenshot seem to indicate encoding issues, since it complains about specific characters that don't seem to print well.

Can you give [this Microsoft doc on VSCode and encodings for PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/understanding-file-encoding?view=powershell-6) a look and see if saving the file using the recommended encoding fixes things for you? This section seems helpful:

> If you work primarily with Windows applications and Windows PowerShell, you should prefer an encoding like UTF-8 with BOM or UTF-16.
If you work across platforms, you should prefer UTF-8 with BOM.
If you work mainly in Linux-associated contexts, you should prefer UTF-8 without BOM.
Windows-1252 and latin-1 are essentially legacy encodings that you should avoid if possible. However, some older Windows applications may depend on them.

**Comment by yvdmeij** [comment]
I've tried it on another file now and this seems to work fine. The issue isn't because of your package, but with Atom itself. 

I've checked the encoding and there is no problem there. Like I said earlier it works fine with VSCode. It's the only file I've had problems with so far with Atom, so I don't know where the problem lays, but I guess that's not your concern. 

Thanks for the help though!! I appreciate it!
